/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UniswapV3SwapInterface extends Interface {
  getFunction(
    nameOrSignature: "swapExactInputMultiHop" | "swapExactInputSingleHop"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "swapExactInputMultiHop",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputSingleHop",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "swapExactInputMultiHop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputSingleHop",
    data: BytesLike
  ): Result;
}

export interface UniswapV3Swap extends BaseContract {
  connect(runner?: ContractRunner | null): UniswapV3Swap;
  waitForDeployment(): Promise<this>;

  interface: UniswapV3SwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  swapExactInputMultiHop: TypedContractMethod<
    [path: BytesLike, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapExactInputSingleHop: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      poolFee: BigNumberish,
      amountIn: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "swapExactInputMultiHop"
  ): TypedContractMethod<
    [path: BytesLike, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactInputSingleHop"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      poolFee: BigNumberish,
      amountIn: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
