/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  UniswapV3Pool,
  UniswapV3PoolInterface,
} from "../../UniswapV3Pool.sol/UniswapV3Pool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "createPool",
    outputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "contract IUniswapV3Factory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a080604052346100465730608052600080546001600160a01b031916731f98431c8ad98523631ae4a59f267346ea31f9841790556101a5908161004c8239608051815050f35b600080fdfe608080604052600436101561001357600080fd5b600090813560e01c908163a167129514610060575063c45a01551461003757600080fd5b3461005d578060031936011261005d57546040516001600160a01b039091168152602090f35b80fd5b90503461016b57606036600319011261016b576001600160a01b03826004358281169081900361016b5760243583811680910361013d576044359062ffffff82168092036101675783869360649385938860209854169263a167129560e01b86526004860152602485015260448401525af191821561015c5783926100ed575b6020838360405191168152f35b90915060203d602011610155575b601f8101601f1916820167ffffffffffffffff8111838210176101415760209183916040528101031261013d5751818116810361013d576020925090386100e0565b8280fd5b634e487b7160e01b85526041600452602485fd5b503d6100fb565b6040513d85823e3d90fd5b8380fd5b5080fdfea264697066735822122093a36dfb49c71b4dd2f21a03748a9ce429be0837b0102c614b1491efaf501c5b64736f6c63430008160033";

type UniswapV3PoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UniswapV3PoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UniswapV3Pool__factory extends ContractFactory {
  constructor(...args: UniswapV3PoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UniswapV3Pool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): UniswapV3Pool__factory {
    return super.connect(runner) as UniswapV3Pool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UniswapV3PoolInterface {
    return new Interface(_abi) as UniswapV3PoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UniswapV3Pool {
    return new Contract(address, _abi, runner) as unknown as UniswapV3Pool;
  }
}
